# Generated by Django 4.1.5 on 2023-01-05 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('data_visita', models.DateTimeField(default=datetime.datetime(2023, 1, 5, 10, 54, 45, 310367))),
                ('evangelico', models.BooleanField(default=False)),
                ('primeira_vez', models.BooleanField(default=True)),
                ('igreja_origem', models.CharField(default='Não pertence a nenhuma igreja', max_length=200)),
                ('pastor', models.CharField(max_length=200)),
                ('observacao', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
