# Generated by Django 4.1.5 on 2023-01-13 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='como_conheceu_igreja',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_visita',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 12, 50, 55, 173068)),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='pastor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
